### ISSUE TITLE
nonce leaks /dev/urandom fds

### ISSUE THREAD

**Issue by osa1** [prowdsponsor/nonce#12]
The library has no `close` function, so once you use this library there will be fd leaks.

Code like `Nonce.new >>= Nonce.nonce128` leaks a fd on each call.

**Comment by erikd** [comment]
At the moment, the file descriptor will be closed when the garbage collector reaps the object. I agree this is less that ideal. I would also like to note that I inherited this project when the original author became too busy or moved on to other things.

I'm open to suggestions. Would a function:

```
withGenerator :: MonadIO m => (a -> m b) -> m b
```

I could add that and then deprecate the `new` function.

**Comment by osa1** [comment]
> At the moment, the file descriptor will be closed when the garbage collector reaps the object.

This definitely does not happen. Could you show me the code that does this (e.g. code that assigns a finalizer that closes the fd on gc) ?

This caused bugs in our project that we had hard time fixing. Literally for months the process leaked fds until it crashed with `EMFILE`. I'm pretty sure these fds are never released (even after gc).

> withGenerator :: MonadIO m => (Generator -> m b) -> m b

This is exactly what I did:

https://github.com/osa1/nonce/commit/87cf628a65aa9f9e5dfaf61c0c5ecfc87a1e8657

I can open a PR.

We're currently using my fork and it fixed the issue.

**Comment by erikd** [comment]
Yes, please open a PR.

**Comment by osa1** [comment]
We have three alternative designs

(1) Keep `new` as-is, implement delete, implement `withGenerator` that works with `IO` callback:


```haskell
-- | Create a new nonce generator using the system entropy.
new :: MonadIO m => m Generator
new = G <$> liftIO Entropy.openHandle

-- | Free the given nonce generator resources.
delete :: MonadIO m => Generator -> m ()
delete (G v) = liftIO $ Entropy.closeHandle v

-- | `bracket new delete`
withGenerator :: (Generator -> IO a) -> IO a
withGenerator = bracket new delete
```

(2) Use `MonadBaseControl` to generalize `withGenerator`:


```haskell
-- | Create a new nonce generator using the system entropy.
new :: MonadBase IO m => m Generator
new = G <$> liftBase Entropy.openHandle

-- | Free the given nonce generator resources.
delete :: MonadBase IO m => Generator -> m ()
delete (G v) = liftBase $ Entropy.closeHandle v

-- | `bracket new delete`
withGenerator :: MonadBaseControl IO m => (Generator -> m a) -> m a
withGenerator = bracket new delete
```

(3) Use `MonadUnliftIO` to generalize `withGenerator`:


```haskell
-- | Create a new nonce generator using the system entropy.
new :: MonadIO m => m Generator
new = G <$> liftIO Entropy.openHandle

-- | Free the given nonce generator resources.
delete :: MonadIO m => Generator -> m ()
delete (G v) = liftIO $ Entropy.closeHandle v

-- | `bracket new delete`
withGenerator :: MonadUnliftIO m => (Generator -> m a) -> m a
withGenerator = bracket new delete
```

Personally I like (3) best because I prefer `MonadUnliftIO` to `MonadBaseControl` and also (3) keeps `new`s type.

Which one should I go with?

**Comment by erikd** [comment]
I  agree, 3) is probably best.
